UserManagement/urls.py
from django.urls import path
from UserManagement.views import main
from Core import views as core_views

app_name = 'user_management'

urlpatterns = [
    # path('', main.get_login_page, name='login_page'),
    path("", main.redirect_to_dashboard, name="redirect_to_dashboard"),
    path('login', main.get_login_page, name='login_page'),
    path('admin', main.get_admin_page, name= 'admin'),
    path('password/', main.change_password, name='change_password'),
    path('dashboard/', main.get_dashboard, name='dashboard'),
    path('get_transaction_summary_lines/<int:item_pk>/', main.get_transaction_summary_lines, name='get_transaction_summary_lines'),
    path('save_changed_password/', main.set_changed_password, name='save_changed_password'),
    path('user', main.authenticate_user, name='authenticate_user'),
    path('accounts/login/', main.change_password, name='login_required_page'),
    path('logout', main.logout_view, name='logout'),
    path('get_audit_report/<int:item_pk>/', main.get_audit_report, name='get_audit_report'),
    path('get_remove_transaction/<int:item_pk>/', main.remove_transaction, name='get_remove_transaction'),
    path('change_password', main.change_password, name='change_password'),
    path('export_transaction_lines', core_views.convert_to_csv, name='export_transaction_lines'),
    path('upload_payload', core_views.upload_payload, name='upload_payload'),
    path('upload_cpt_codes', core_views.upload_cpt_codes, name='upload_cpt_codes'),
    path('download_cpt_codes_as_csv', core_views.download_cpt_codes_as_csv, name='download_cpt_codes_as_csv'),
    path('filter_transaction_lines', core_views.filter_transaction_lines, name='filter_transaction_lines'),


]

UserManagement/templates/UserManagement/Dashboard/AuditReport.html
{% extends 'base_component.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}

{% block content %}

    <div class="row" id="department_mappings">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Transaction Summary</h4>
                </div>

                <div class="row">

                    <div class="col-md-2">

                        <h4 class="mb-3 text-primary" align="center">Transactions ID: {{ item_pk }}<i><b></b></i></h4>

                    </div>


                    <div class="col-md-3">
                        <h6>Transaction status:</h6>
                        <select class="select_field_class" name="option" id="option">
                            <option value=""></option>
                            <option value="pass">Successful</option>
                            <option value="fail">Failed</option>
                        </select>
                    </div>

                    <div class="col-md-3">

                        <h6>*</h6>
                        <button type="button" class="btn btn-primary round width-200 buttonAnimation" id="btn_filter" data-animation="pulse" data-toggle="modal" data-backdrop="static" data-target="#modalCategoryMapping">
                            <i class="la la-download"></i> Filter records
                        </button>

                    </div>


                    <div class="col-md-3">
                        <h6>Click below to download CSV file based on the selected filters</h6>
                        <button type="button" id="btn_download" class="btn btn-outline-primary block btn-md" data-toggle="modal" data-target="#default">
                            <i class="la la-download"></i>Download Payload
                        </button>
                    </div>


                </div>

                <div class="card-body">

                    <div id="transaction_lines_table">
                        <div class="table-responsive">

                            {% render_table table_transactions %}

                        </div>

                        <div style="clear: both">
                            <h4 id="id_count" style="float: left">Total Records: {{ table_transactions.rows|length }}</h4>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>



{% endblock %}

{% block scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script>

        $("#btn_filter").on("click", function () {

            var status = $('.select_field_class').val().toString();
            var id = {{ item_pk }};
            var url = "{% url 'user_management:filter_transaction_lines' %}";

            $("#dashboard_elements").empty();


            $.ajax({
                type: "POST",
                url: url,
                data: {
                    status: status,item_pk:id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },

                success: function (data) {


                    $("#transaction_lines_table").html(data);

                    $("#filter_spinner").hide();

                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {

                    swal("Failed", "Failed to load Dashboard content.", "warning");

                }
            });


        });


        $("#btn_download").on( "click", function( event ) {
            var id = {{ item_pk }};
            var url = '{% url 'user_management:export_transaction_lines' %}';
            var status = $('.select_field_class').val().toString();

            var dateTimeNow = new Date($.now()).toString().match(/\d{2}:\d{2}:\d{2}/)[0];

            $.ajax({
                type: "POST",
                url: url,
                data: {
                    item_pk: id,status:status,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(data)
                {
                    var uri = 'data:application/csv;charset=UTF-8,' + encodeURIComponent(data);

                    var downloadLink = document.createElement("a");
                    downloadLink.href = uri;
                    downloadLink.download = "payload_"+dateTimeNow+".csv";

                    document.body.appendChild(downloadLink);
                    downloadLink.click();
                    document.body.removeChild(downloadLink);


                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {

                    swal({
                        title: 'Operation failed.',
                        icon: 'error'
                    });

                }
            });

            e.preventDefault(); // avoid to execute the actual submit of the form.

        });


        $('.select_field_class').select2({placeholder: "Select Transaction status", maximumSelectionSize: 100});

    </script>

{% endblock %}

UserManagement/templates/UserManagement/Dashboard/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}


{% block content %}

    <div class="row" id="transaction_summary">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Transaction Summary</h4>
                </div>


                <div class ="row" style="padding-top: 30px; padding-left: 30px;">
                    <div class="col-md-2">
                         <button type="button" class="btn btn-outline-primary block btn-md" data-toggle="modal" data-target="#default">
                        <i class="la la-arrow-up"></i>Upload Payload
                    </button>
                    </div>
                    <div class="col-md-2">
                           <button type="button" class="btn btn-outline-success block btn-md" data-toggle="modal" data-target="#view-uploads">
                        <i class="la la-eye"></i>View Uploaded files
                    </button>
                    </div>
                </div>

                <div class="card-body">

                    <div class="table-responsive">

                        {% render_table transaction_summary_table %}

                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="form-group">
            <!-- Modal -->
            <div class="modal fade text-left" id="default" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
                <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel1">Upload Payload</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                            <form method = "POST" action="{% url 'user_management:upload_payload' %}" enctype="multipart/form-data">

                                {% csrf_token %}

                                <table>

                                    {% crispy payload_form %}


                                </table>

                                <div class="modal-footer">
                                    <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-outline-primary">Upload</button>
                                </div>

                            </form>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="form-group">
            <!-- Modal -->
            <div class="modal fade text-left" id="view-uploads" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel1">View Uploads</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                            <div class="table-responsive">

                                {% render_table uploads_table %}

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="form-group">
            <!-- Modal -->
            <div class="modal fade text-left" id="view_more" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel1">Transaction Summary Lines</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block scripts %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script>

        jQuery.noConflict();
        $(document).ready(function(){

            {#            jQuery('#file').trigger('click');#}

            $(".btn_audit_report").on( "click", function( event ) {

                var item = $(this).attr("id");
                var url = '{% url 'user_management:get_audit_report' 12345 %}'.replace(/12345/, parseInt(item));

                window.open(url, '_blank');

            });


            $('.btn_delete').on("click", function(event)
            {
                var item = $(this).attr("id");
                var url = '{% url 'user_management:get_remove_transaction' 12345 %}'.replace(/12345/, parseInt(item));

                swal({
                    title: "Are you sure you want to remove this transaction?",
                    text: ".",
                    icon: "warning",
                    buttons: [
                        'No, cancel it!',
                        'Yes, I am sure!'
                    ],
                    dangerMode: true,
                }).then(function(isConfirm) {
                    if (isConfirm) {
                        {
                            $.ajax({
                                type: "POST",
                                url: url,
                                data: {
                                    item: item,
                                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                                },
                                success: function (data) {

                                    swal("Success!", "Removed successfully.", "success");
                                    location.reload();

                                },
                                error: function (XMLHttpRequest, textStatus, errorThrown) {

                                    swal("Removing item Failed.", "Error thrown: "+errorThrown+" ", "error");

                                }
                            });

                            e.preventDefault(); // avoid to execute the actual submit of the form.
                        }
                    }

                    else {

                        swal("Info", "Action cancelled by user.", "info");
                    }

                });

                e.preventDefault(); // avoid to execute the actual submit of the form.

            });

            $(".btn_download").on( "click", function( event ) {
                var id = $(this).attr('id');
                var url = '{% url 'user_management:export_transaction_lines' %}';

                var dateTimeNow = new Date($.now()).toString().match(/\d{2}:\d{2}:\d{2}/)[0];

                $.ajax({
                    type: "POST",
                    url: url,
                    data: {
                        item_pk: id,status:"",
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(data)
                    {
                        var uri = 'data:application/csv;charset=UTF-8,' + encodeURIComponent(data);

                        var downloadLink = document.createElement("a");
                        downloadLink.href = uri;
                        downloadLink.download = "payload_transaction_"+id+"_"+dateTimeNow+".csv";

                        document.body.appendChild(downloadLink);
                        downloadLink.click();
                        document.body.removeChild(downloadLink);


                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {

                        swal({
                            title: 'Operation failed.',
                            icon: 'error'
                        });

                    }
                });

                e.preventDefault(); // avoid to execute the actual submit of the form.

            });

        });

        function downloadExcel(fileName, tableId){

            let dataType = 'application/vnd.ms-excel';
            let extension = '.xls';
            let filename = fileName;

            let base64 = function(s) {
                return window.btoa(unescape(encodeURIComponent(s)))
            };

            let template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>';
            let render = function(template, content) {
                return template.replace(/{(\w+)}/g, function(m, p) { return content[p]; });
            };

            let tableElement = document.getElementById(''+tableId+'');

            let tableExcel = render(template, {
                worksheet: filename,
                table: tableElement.innerHTML
            });

            filename = filename + extension;

            if (navigator.msSaveOrOpenBlob)
            {
                let blob = new Blob(
                        [ '\ufeff', tableExcel ],
                        { type: dataType }
                );

                navigator.msSaveOrOpenBlob(blob, filename);
            } else {
                let downloadLink = document.createElement("a");

                document.body.appendChild(downloadLink);

                downloadLink.href = 'data:' + dataType + ';base64,' + base64(tableExcel);

                downloadLink.download = filename;

                downloadLink.click();
            }
        }

        $('.select_field_class').select2( { placeholder: "Select Message type", maximumSelectionSize: 100  } );

    </script>



{% endblock %}