API/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register('transactions_summary', views.TransactionSummaryView)
router.register('services_received', views.ServiceReceivedView)
router.register('death_by_disease_cases_at_facility', views.DeathByDiseaseCaseAtFacilityView)
router.register('death_by_disease_cases_not_at_facility', views.DeathByDiseaseCaseNotAtFacilityView)
router.register('bed_occupancy', views.BedOccupancyView)
router.register('revenue_received', views.RevenueReceivedView)
router.register('icd10', views.ICD10View)
router.register('cpt', views.CPTCodeView)
router.register('nhif_claims', views.ClaimsView)


urlpatterns = [
    path('', include(router.urls))

]

HDR/urls.py
from django.contrib import admin
from django.urls import path, include
from UserManagement.views import main as user_management_views
from Core import tasks as core_tasks
from DHIS import tasks as dhis_tasks

urlpatterns = [

    # path('', include('UserManagement.urls')),
    path("", include(("UserManagement.urls", "user_management"), namespace="user_management")),

    # path('authenticate', api_views.authenticate_user, name='authenticate'),
    path('admin/', admin.site.urls),
    path('get_', include('MasterData.urls')),
    path('api_', include('API.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('change_password', user_management_views.change_password, name="change_password"),
    path('calculate_and_save_bed_occupancy_rate', core_tasks.calculate_and_save_bed_occupancy_rate,
         name='calculate_and_save_bed_occupancy_rate'),
    path('create_claims_payload', dhis_tasks.create_claims_payload, name='create_claims_payload'),
    path('create_death_payload', dhis_tasks.create_death_payload, name='create_death_payload'),
    path('save_payload_from_csv', core_tasks.save_payload_from_csv, name='save_payload_from_csv'),
    path('cleanup_uploaded_csv_files', core_tasks.cleanup_uploaded_csv_files, name='cleanup_uploaded_csv_files'),

]

UserManagement/urls.py
from django.urls import path
from UserManagement.views import main
from Core import views as core_views

app_name = 'user_management'

urlpatterns = [
    # path('', main.get_login_page, name='login_page'),
    path("", main.redirect_to_dashboard, name="redirect_to_dashboard"),
    path('login', main.get_login_page, name='login_page'),
    path('admin', main.get_admin_page, name= 'admin'),
    path('password/', main.change_password, name='change_password'),
    path('dashboard/', main.get_dashboard, name='dashboard'),
    path('get_transaction_summary_lines/<int:item_pk>/', main.get_transaction_summary_lines, name='get_transaction_summary_lines'),
    path('save_changed_password/', main.set_changed_password, name='save_changed_password'),
    path('user', main.authenticate_user, name='authenticate_user'),
    path('accounts/login/', main.change_password, name='login_required_page'),
    path('logout', main.logout_view, name='logout'),
    path('get_audit_report/<int:item_pk>/', main.get_audit_report, name='get_audit_report'),
    path('get_remove_transaction/<int:item_pk>/', main.remove_transaction, name='get_remove_transaction'),
    path('change_password', main.change_password, name='change_password'),
    path('export_transaction_lines', core_views.convert_to_csv, name='export_transaction_lines'),
    path('upload_payload', core_views.upload_payload, name='upload_payload'),
    path('upload_cpt_codes', core_views.upload_cpt_codes, name='upload_cpt_codes'),
    path('download_cpt_codes_as_csv', core_views.download_cpt_codes_as_csv, name='download_cpt_codes_as_csv'),
    path('filter_transaction_lines', core_views.filter_transaction_lines, name='filter_transaction_lines'),


]

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <title>Health Data Repository</title>

    {%  load static %}

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="HDR Admin Panel for the configuration and mapping of Facility masterdata">
    <meta name="keywords" content="Masterdata mappings and transaction status monitoring">
    <meta name="author" content="MOH">
    <title>Health Data Repository</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static "app-assets/images/ico/favicon.ico" %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/vendors.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/bootstrap-extended.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/colors.css" %}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jstree/3.3.8/themes/default/style.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/components.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/core/menu/menu-types/vertical-menu.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/core/colors/palette-gradient.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/pages/hospital.css" %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.8/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "assets/css/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/custom.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/jqtree.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "line-awesome/css/line-awesome.min.css" %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />



</head>


<!-- BEGIN: Header-->
<body class="vertical-layout vertical-menu 2-columns   fixed-navbar" data-open="click" data-menu="vertical-menu" data-col="2-columns">

<!-- BEGIN: Header-->
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-light bg-info navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item"><a class="navbar-brand" href=""><img class="brand-logo" alt="modern admin logo" src="{% static "app-assets/images/tanzania_logo.png" %}">
                    <h3 class="brand-text">HDR Admin Panel</h3>
                </a></li>
                <li class="nav-item d-md-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu"></i></a></li>
                    <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>
                </ul>
                <ul class="nav navbar-nav float-right">

                    <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown"><span class="mr-1 user-name text-bold-700"> {{ user }}</span></a>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" id="change_password" href="{%  url "change_password" %}"><i class="ft-user"></i>Change Password</a>
                            <div class="dropdown-divider"></div><a class="dropdown-item" href="{% url 'user_management:logout' %}" id="id_logout"><i class="ft-power"></i> Logout</a>
                            <div class="dropdown-divider"></div><a class="dropdown-item"><i></i><p style="color:red"> Access Level : {{ user.profile.facility }}</p></a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- END: Header-->


<!-- BEGIN: Main Menu-->

<div class="main-menu menu-fixed menu-light menu-accordion    menu-shadow " data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

            <li class="navigation-header"><span data-i18n="nav.category.professional"><b><a href="{% url 'user_management:dashboard' %}">Transaction Summary</a></b></span><i class="la la-ellipsis-h" data-toggle="tooltip" data-placement="right" data-original-title="Professional"></i>
            </li>

        </ul>

        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

            <li class=" navigation-header"><span data-i18n="nav.category.professional"><b>Masterdata Mappings</b></span><i class="la la-ellipsis-h" data-toggle="tooltip" data-placement="right" data-original-title="Professional"></i>
            </li>

            <li class=" nav-item" id="btn_departments"><a href="{% url 'get_departments_page' %}"><i class="la la-building"></i><span class="menu-title" data-i18n="">Departments</span></a>
            </li>

            <li class=" nav-item" id="btn_exemptions"><a href="{% url 'get_exemptions_page' %}"><i class="la la-group"></i><span class="menu-title" data-i18n="">Exemptions</span></a>
            </li>

            <li class=" nav-item" id="btn_payers"><a href="{% url 'get_payers_page' %}"><i class="la la-money"></i><span class="menu-title" data-i18n="">Payers</span></a>
            </li>

            <li class=" nav-item" id="btn_wards"><a href="{% url 'get_wards_page' %}"><i class="la la-bed"></i><span class="menu-title" data-i18n="">Wards</span></a>
            </li>

            <li class=" nav-item" id="btn_wards"><a href="{% url 'get_gender_page' %}"><i class="la la-mars"></i><span class="menu-title" data-i18n="">Gender</span></a>
            </li>

             <li class=" nav-item" id="btn_wards"><a href="{% url 'get_places_of_death_page' %}"><i class="la la-map"></i><span class="menu-title" data-i18n="">Places Of Death</span></a>
            </li>


             <li class=" nav-item" id="btn_wards"><a href="{% url 'get_service_provider_rankings_page' %}"><i class="la la-hospital-o"></i><span class="menu-title" data-i18n=""> Rankings</span></a>
            </li>

            <li class=" nav-item" id="btn_cpt_codes"><a href="{% url 'cpt_codes_page' %}"><i class="la la-scissors"></i><span class="menu-title" data-i18n="">CPT Codes</span></a>
            </li>


        </ul>
    </div>
</div>


<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-header row mb-1">
        </div>
        <div class="content-body">

            <div class="col-lg-4 col-md-12 col-sm-12">
                <div class="form-group">
                    <!-- Popup Modal -->
                    <div id="popModal" class="modal fade text-left" tabindex="-1" aria-hidden="true" aria-labelledby="myModalLabel70" role="dialog" data-keyboard="false" data-backdrop="static">


                    </div>

                </div>
            </div>


            {% block content %}




            {% endblock %}


        </div>
    </div>
</div>


<div class="sidenav-overlay"></div>
<div class="drag-target"></div>


<script src="{% static "app-assets/vendors/js/vendors.min.js" %}"></script>
<script src="{% static "app-assets/js/core/app-menu.js" %}"></script>
<script src="{% static "app-assets/js/core/app.js" %}"></script>
<script src="{% static "app-assets/js/scripts/pages/appointment.js" %}"></script>
{#<script src="{% static "app-assets/vendors/js/extensions/jquery.steps.min.js" %}"></script>#}
<script src="{% static "app-assets/vendors/js/pickers/dateTime/moment-with-locales.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/pickers/daterange/daterangepicker.js" %}"></script>
<script src="{% static "app-assets/vendors/js/extensions/sweetalert.min.js" %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/maps/modules/offline-exporting.js"></script>
<script src="{% static "js/tree.jquery.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static "app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/forms/toggle/bootstrap-switch.min.js" %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>


<script>

    $(document).ready(function(){




    });

</script>


{% block scripts %}



{% endblock %}


</body>
</html>

templates/base_component.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Health Data Repository Admin Panel</title>

    {%  load static %}

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/plugins/loaders/loaders.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/core/colors/palette-loader.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/custom.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "app-assets/images/ico/favicon.ico" %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/vendors.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/extensions/bootstrap-treeview.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/bootstrap-extended.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/colors.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/components.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/ui/jquery-ui.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/core/menu/menu-types/vertical-compact-menu.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/fonts/mobiriseicons/24px/mobirise/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/charts/jquery-jvectormap-2.0.3.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/charts/morris.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/fonts/simple-line-icons/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/core/colors/palette-gradient.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/charts/chartist.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/charts/chartist-plugin-tooltip.css" %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "app-assets/images/ico/favicon.ico" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/vendors.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/pickers/daterange/daterangepicker.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/bootstrap-extended.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/colors.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/components.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "assets/css/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/pickers/daterange/daterangepicker.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/plugins/forms/wizard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/plugins/pickers/daterange/daterange.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/plugins/extensions/toastr.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/plugins/ui/jqueryui.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/pages/timeline.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/editors/summernote.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/editors/codemirror.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/vendors/css/editors/theme/monokai.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "app-assets/css/pages/app-chat.css" %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jstree/3.3.8/themes/default/style.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static "css/custom.css" %}">

</head>

{%  block content %}








{%  endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="{% static "app-assets/vendors/js/vendors.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/charts/chart.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/charts/raphael-min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/charts/morris.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/charts/jvector/jquery-jvectormap-2.0.3.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/charts/jvector/jquery-jvectormap-world-mill.js" %}"></script>
<script src="{% static "app-assets/data/jvector/visitor-data.js" %}"></script>
<script src="{% static "app-assets/js/core/app-menu.js" %}"></script>
<script src="{% static "app-assets/js/core/app.js" %}"></script>
<script src="{% static "app-assets/js/scripts/pages/dashboard-sales.js" %}"></script>
<script src="{% static "app-assets/vendors/js/extensions/jquery.steps.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/pickers/dateTime/moment-with-locales.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/pickers/daterange/daterangepicker.js" %}"></script>
<script src="{% static "app-assets/vendors/js/forms/validation/jquery.validate.min.js" %}"></script>
<script src="{% static "app-assets/js/scripts/forms/wizard-steps.js" %}"></script>
<script src="{% static "app-assets/vendors/js/extensions/listjs/list.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/extensions/listjs/list.fuzzysearch.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/extensions/listjs/list.pagination.min.js" %}"></script>
<script src="{% static "app-assets/js/scripts/extensions/list.js" %}"></script>
<script src="{% static "app-assets/vendors/js/extensions/sweetalert.min.js" %}"></script>
<script src="{% static "app-assets/js/scripts/extensions/sweet-alerts.js" %}"></script>
<script src="{% static "app-assets/vendors/js/animation/jquery.appear.js" %}"></script>
<script src="{% static "app-assets/js/scripts/animation/animation.js" %}"></script>
<script src="{% static "app-assets/js/scripts/forms/switch.js" %}"></script>
<script src="{% static "app-assets/js/scripts/dropdowns/dropdowns.js" %}"></script>
<script src="{% static "app-assets/vendors/js/forms/icheck/icheck.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/extensions/toastr.min.js" %}"></script>
<script src="{% static "app-assets/js/scripts/extensions/toastr.js" %}"></script>
<script src="{% static "app-assets/js/core/libraries/jquery_ui/jquery-ui.min.js" %}"></script>
<script src="{% static "app-assets/js/scripts/ui/jquery-ui/date-pickers.js" %}"></script>
<script src="{% static "app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/forms/toggle/bootstrap-switch.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/forms/toggle/switchery.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/extensions/bootstrap-treeview.min.js" %}"></script>
<script src="{% static "app-assets/js/scripts/pages/app-email.js" %}"></script>
<script src="{% static "app-assets/js/scripts/pages/app-chat.js" %}"></script>
<script src="{% static "app-assets/vendors/js/pickers/dateTime/moment-with-locales.min.js" %}"></script>
<script src="{% static "app-assets/vendors/js/pickers/daterange/daterangepicker.js" %}"></script>
<script src="{% static "app-assets/js/scripts/dropdowns/dropdowns.js" %}"></script>
<script src="{% static "app-assets/js/scripts/ui/jquery-ui/date-pickers.js" %}"></script>


{% block scripts %}



{% endblock %}

</html>